apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspectorgadget  
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspectorgadget
  template:
    metadata:
      labels:
        app: inspectorgadget
    spec:
      containers:
      - name: inspectorgadget
        image: ghcr.io/jelledruyts/inspectorgadget:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inspectorgadget
  namespace: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: inspectorgadget