config:
  azureCloudConfig:
    cloud: "AzurePublicCloud"
    tenantId: "<tenant ID>"
    subscriptionId: "<subscription ID>"
    useManagedIdentityExtension: true
    userAssignedIdentityID: "<user assigned msi clientID>"
    userAgent: "kube-egress-gateway-controller"
    resourceGroup: "<resource group name>"
    location: "<resource group location>"
    gatewayLoadBalancerName: "kubeegressgateway-ilb"
    loadBalancerResourceGroup: ""
    vnetName: "<virtual network name>"
    vnetResourceGroup: ""
    subnetName: "<subnet name>"