name: Spell Check Markdown

on:
  pull_request:
    branches: [main]
  push: 
    branches: [main]

  workflow_dispatch:

jobs:
  spell-ckeck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0

      - uses: streetsidesoftware/cspell-action@v3
        name: Spell Check
        continue-on-error: true
        with:
          # Github token used to fetch the list of changed files in the commit.
          # Default: ${{ github.token }}
          github_token: ${{ github.token }}
          config: './.spell_check/cspell.json'
          
          # Notification level to use with inline reporting of spelling errors.
          # Allowed values are: warning, error, none
          # Default: warning
          inline: warning

          # The point in the directory tree to start spell checking.
          # Default: .
          root: '.'
          
          # Define glob patterns to filter the files to be checked. Use a new line between patterns to define multiple patterns.
          # The default is to check ALL files that were changed in in the pull_request or push.
          # Note: `ignorePaths` defined in cspell.json still apply.
          # Example:
          # files: |
          #   **/*.{ts,js}
          #   !dist/**/*.{ts,js}
          #   # Hidden directories need an explicit .* to be included
          #   .*/**/*.yml
          #
          # To not check hidden files, use:
          # files: "**"
          #
          # Default: ALL files
          files: |
            **/*.md
            !dist/**/*.{ts,js}

          # Check files and directories starting with `.`.
          # - "true" - glob searches will match against `.dot` files.
          # - "false" - `.dot` files will NOT be checked.
          # - "explicit" - glob patterns can match explicit `.dot` patterns.
          check_dot_files: false

          # Determines if the action should be failed if any spelling issues are found.
          # Allowed values are: true, false
          # Default: true
          strict: true

          # Limit the files checked to the ones in the pull request or push.
          incremental_files_only: false

          # Log progress and other information during the action execution.
          # Default: false
          verbose: false
